"""
Professional PDF Report Generator for SecureCode AI.
Generates multi-page, branded security analysis reports using ReportLab.
Uses only the pre-generated scan results sent from the frontend without issuing any LLM calls.
"""

import io
import html
import re
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Preformatted,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas


def xml_escape(val: Any) -> str:
    """Escapes XML special characters (&, <, >) to avoid ReportLab ParaParser syntax errors."""
    if val is None:
        return ""
    text = str(val)
    # Strip illegal XML control characters (except newline, carriage return, and tab)
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", text)
    return html.escape(text, quote=False)


class NumberedCanvas(canvas.Canvas):
    """Adds 'Page X of Y' and confidential watermark to every page."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Top Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "SecureCode AI — Confidential Security Analysis Report")
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(54, 744, 558, 744)

        # Bottom Footer
        page_str = f"Page {self._pageNumber} of {max(page_count, 1)}"
        self.drawRightString(558, 36, page_str)
        self.drawString(54, 36, "Generated by SecureCode AI Platform • Automated Security Review")
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(54, 46, 558, 46)

        self.restoreState()


def generate_security_pdf(data: Dict[str, Any]) -> bytes:
    """
    Generates a PDF byte stream from the frontend report payload.
    Safely handles arbitrary sized code, rich AI insights, and multi-page layouts.
    """
    if not isinstance(data, dict):
        data = {}

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0f172a"),
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#475569"),
    )
    h1_style = ParagraphStyle(
        "SectionH1",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True,
    )
    h2_style = ParagraphStyle(
        "SectionH2",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#334155"),
        spaceBefore=6,
        spaceAfter=3,
        keepWithNext=True,
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12.5,
        textColor=colors.HexColor("#334155"),
    )
    callout_style = ParagraphStyle(
        "CalloutBox",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12.5,
        textColor=colors.HexColor("#1e3a8a"),
        backColor=colors.HexColor("#eff6ff"),
        borderColor=colors.HexColor("#bfdbfe"),
        borderWidth=0.5,
        borderPadding=8,
        spaceAfter=10,
    )
    code_style = ParagraphStyle(
        "CodeTextCustom",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=7.5,
        leading=10.5,
        textColor=colors.HexColor("#0f172a"),
        backColor=colors.HexColor("#f8fafc"),
        borderColor=colors.HexColor("#cbd5e1"),
        borderWidth=0.5,
        borderPadding=8,
        spaceAfter=10,
    )

    story = []

    # Title & Header
    story.append(Paragraph("SecureCode AI", title_style))
    story.append(Paragraph("Automated Vulnerability & Security Code Review Report", subtitle_style))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#3b82f6"), spaceAfter=12))

    # File & Scan Metadata Table
    file_name = str(data.get("file_name") or "untitled")
    language = str(data.get("language") or data.get("detected_language") or "Unknown")

    analysis_time = data.get("analysis_time_ms")
    if analysis_time is None:
        analysis_time = data.get("analysis_time_seconds")
        if analysis_time is not None:
            try:
                analysis_time = round(float(analysis_time) * 1000, 1)
            except Exception:
                pass
    if analysis_time is None:
        analysis_time = 0

    score = data.get("security_score")
    if score is None:
        score = 100

    vulns_raw = data.get("vulnerabilities")
    vulns = [v for v in vulns_raw if isinstance(v, dict)] if isinstance(vulns_raw, list) else []

    issues_found = data.get("issues_found")
    if issues_found is None:
        issues_found = len(vulns)

    meta_data = [
        [
            Paragraph("<b>Target File:</b>", body_style),
            Paragraph(xml_escape(file_name), body_style),
            Paragraph("<b>Language:</b>", body_style),
            Paragraph(xml_escape(language), body_style),
        ],
        [
            Paragraph("<b>Security Score:</b>", body_style),
            Paragraph(f"<b>{xml_escape(score)}/100</b>", body_style),
            Paragraph("<b>Issues Found:</b>", body_style),
            Paragraph(xml_escape(issues_found), body_style),
        ],
        [
            Paragraph("<b>Analysis Time:</b>", body_style),
            Paragraph(f"{xml_escape(analysis_time)} ms", body_style),
            Paragraph("<b>Review Status:</b>", body_style),
            Paragraph("Completed", body_style),
        ],
    ]
    t_meta = Table(meta_data, colWidths=[90, 160, 90, 164])
    t_meta.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ])
    )
    story.append(t_meta)
    story.append(Spacer(1, 12))

    # Severity Counts Breakdown
    counts = data.get("severity_counts")
    if not isinstance(counts, dict):
        counts = {}
    crit_c = counts.get("critical", 0) or 0
    high_c = counts.get("high", 0) or 0
    med_c = counts.get("medium", 0) or 0
    low_c = counts.get("low", 0) or 0

    sev_data = [
        [
            Paragraph("<b>CRITICAL</b>", body_style),
            Paragraph("<b>HIGH</b>", body_style),
            Paragraph("<b>MEDIUM</b>", body_style),
            Paragraph("<b>LOW</b>", body_style),
        ],
        [
            Paragraph(f"<font color='#dc2626'><b>{xml_escape(crit_c)}</b></font>", body_style),
            Paragraph(f"<font color='#ea580c'><b>{xml_escape(high_c)}</b></font>", body_style),
            Paragraph(f"<font color='#ca8a04'><b>{xml_escape(med_c)}</b></font>", body_style),
            Paragraph(f"<font color='#16a34a'><b>{xml_escape(low_c)}</b></font>", body_style),
        ],
    ]
    t_sev = Table(sev_data, colWidths=[126, 126, 126, 126])
    t_sev.setStyle(
        TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#ffffff")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(t_sev)
    story.append(Spacer(1, 12))

    # AI Security Insight
    insight = data.get("ai_security_insight")
    if not isinstance(insight, dict):
        insight = {}
    why_it_matters = insight.get("why_it_matters")
    potential_impact = insight.get("potential_impact")
    if why_it_matters or potential_impact:
        story.append(Paragraph("AI Security Insight", h1_style))
        parts = []
        if why_it_matters:
            parts.append(f"<b>Why It Matters:</b> {xml_escape(why_it_matters)}")
        if potential_impact:
            parts.append(f"<b>Potential Impact:</b> {xml_escape(potential_impact)}")
        insight_p = "<br/><br/>".join(parts)
        story.append(Paragraph(insight_p, callout_style))
        story.append(Spacer(1, 8))

    # Remediation
    remed = data.get("ai_remediation")
    if not isinstance(remed, dict):
        remed = {}
    actions = remed.get("actions") or []
    if not isinstance(actions, list):
        actions = []
    if remed.get("summary") or remed.get("title") or actions:
        story.append(Paragraph("Recommended Remediation Strategy", h1_style))
        if remed.get("title"):
            story.append(Paragraph(f"<b>Strategy:</b> {xml_escape(remed.get('title'))}", body_style))
        if remed.get("summary"):
            story.append(Paragraph(xml_escape(remed.get("summary")), body_style))
        story.append(Spacer(1, 4))
        if actions:
            for act in actions:
                story.append(Paragraph(f"• {xml_escape(act)}", body_style))
        story.append(Spacer(1, 12))

    # Detected Vulnerabilities
    story.append(Paragraph(f"Detailed Vulnerability Findings ({len(vulns)})", h1_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1"), spaceAfter=10))

    if not vulns:
        story.append(Paragraph("No vulnerabilities detected in the analyzed source code.", body_style))
        story.append(Spacer(1, 12))
    else:
        for idx, v in enumerate(vulns, start=1):
            v_type = xml_escape(v.get("type") or v.get("title") or "Security Issue")
            sev = xml_escape(str(v.get("severity") or "LOW").upper())
            cwe = xml_escape(v.get("cwe") or "N/A")
            owasp = xml_escape(v.get("owasp") or "N/A")
            p_line = xml_escape(v.get("line") or v.get("primary_line") or v.get("primaryLine") or 0)

            raw_aff = v.get("affected_lines")
            if isinstance(raw_aff, list) and raw_aff:
                aff_lines = xml_escape(", ".join(str(l) for l in raw_aff))
            else:
                aff_lines = xml_escape(str(p_line))

            desc = xml_escape(v.get("description") or v.get("short") or "No description provided.")
            why = xml_escape(v.get("why") or v.get("ai_why") or "")
            impact = xml_escape(v.get("impact") or v.get("ai_impact") or "")
            fix = xml_escape(v.get("fix") or v.get("ai_fix") or "")
            method = xml_escape(v.get("analysis_method") or "Static Analysis")
            conf = xml_escape(v.get("confidence") or 85)

            # Severity badge color
            color_hex = "#dc2626" if sev == "CRITICAL" else ("#ea580c" if sev == "HIGH" else ("#ca8a04" if sev == "MEDIUM" else "#16a34a"))

            vuln_elements = [
                Paragraph(
                    f"<b>#{idx}. {v_type}</b> — <font color='{color_hex}'><b>[{sev}]</b></font> (Confidence: {conf}%)",
                    h2_style,
                ),
                Paragraph(f"<b>CWE:</b> {cwe} | <b>OWASP:</b> {owasp} | <b>Line:</b> {p_line} | <b>Affected:</b> {aff_lines}", body_style),
                Paragraph(f"<b>Method:</b> {method}", body_style),
                Spacer(1, 3),
                Paragraph(f"<b>Description:</b> {desc}", body_style),
            ]
            if why:
                vuln_elements.append(Paragraph(f"<b>Why It Matters:</b> {why}", body_style))
            if impact:
                vuln_elements.append(Paragraph(f"<b>Impact:</b> {impact}", body_style))
            if fix:
                vuln_elements.append(Paragraph(f"<b>Remediation:</b> {fix}", body_style))

            # Render evidence snippets if available
            ev_list = v.get("evidence") or []
            if isinstance(ev_list, list):
                for ev in ev_list[:3]:
                    if isinstance(ev, dict) and ev.get("code"):
                        snippet = xml_escape(str(ev.get("code")).strip()[:140])
                        ev_line = xml_escape(ev.get("line", p_line))
                        vuln_elements.append(Paragraph(f"<b>Code Evidence (L{ev_line}):</b> <font face='Courier' size='8'>{snippet}</font>", body_style))

            vuln_elements.append(Spacer(1, 6))
            vuln_elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#f1f5f9"), spaceAfter=8))
            story.append(KeepTogether(vuln_elements))

    # Time & Space Complexity / Comparison
    comp = data.get("ai_comparison")
    if comp and isinstance(comp, dict):
        orig_sec = xml_escape(comp.get("original_security_status") or "Higher Risk")
        corr_sec = xml_escape(comp.get("corrected_security_status") or "Safer")
        orig_t = xml_escape(comp.get("original_time_complexity") or "N/A")
        corr_t = xml_escape(comp.get("corrected_time_complexity") or "N/A")
        orig_s = xml_escape(comp.get("original_space_complexity") or "N/A")
        corr_s = xml_escape(comp.get("corrected_space_complexity") or "N/A")

        story.append(Paragraph("Security Fix & Complexity Comparison", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1"), spaceAfter=8))

        comp_data = [
            [Paragraph("<b>Metric</b>", body_style), Paragraph("<b>Original Implementation</b>", body_style), Paragraph("<b>Secure Implementation</b>", body_style)],
            [Paragraph("Security Status", body_style), Paragraph(orig_sec, body_style), Paragraph(corr_sec, body_style)],
            [Paragraph("Time Complexity", body_style), Paragraph(orig_t, body_style), Paragraph(corr_t, body_style)],
            [Paragraph("Space Complexity", body_style), Paragraph(orig_s, body_style), Paragraph(corr_s, body_style)],
        ]
        t_comp = Table(comp_data, colWidths=[120, 192, 192])
        t_comp.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        story.append(t_comp)
        story.append(Spacer(1, 6))

        if comp.get("complexity_reason"):
            story.append(Paragraph(f"<b>Complexity Analysis:</b> {xml_escape(comp.get('complexity_reason'))}", body_style))
            story.append(Spacer(1, 4))
        if comp.get("final_recommendation"):
            story.append(Paragraph(f"<b>Final Recommendation:</b> {xml_escape(comp.get('final_recommendation'))}", body_style))
            story.append(Spacer(1, 12))

    # Secure Corrected Code Section
    sec_code = data.get("secure_code") or data.get("code")
    if sec_code and isinstance(sec_code, str) and sec_code.strip():
        story.append(Paragraph("Recommended Secure Code", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1"), spaceAfter=6))
        
        # Soft-wrap long lines at 100 characters to prevent overflow and split cleanly across pages
        wrapped_lines = []
        for line in sec_code.splitlines()[:300]:
            while len(line) > 100:
                wrapped_lines.append(line[:100])
                line = "    " + line[100:]
            wrapped_lines.append(line)
        code_text = "\n".join(wrapped_lines)
        story.append(Preformatted(code_text, code_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
