import { useState } from "react";
import { useLocation, useNavigate, Link } from "react-router-dom";

import {
  ShieldCheck,
  RotateCcw,
  CircleCheck,
  TriangleAlert,
  Bug,
  Code2,
  FileCode2,
  Sparkles,
  ShieldAlert,
  Download,
  Lightbulb,
  CircleAlert,
  Copy,
  Check,
  Clock,
  ChevronDown,
  ChevronUp,
  ScanSearch,
  WandSparkles,
} from "lucide-react";

import "./Dashboard.css";


const demoVulnerabilities = [
  {
    id: 1,
    severity: "HIGH",
    title: "Unsafe Input Handling",
    line: "Line 03",
    short:
      "Potentially unsafe user-controlled input handling was detected.",
    why:
      "The input is accepted without sufficient length validation or defensive checks before being processed.",
    impact:
      "Improper handling of user-controlled input may cause unexpected application behaviour and can introduce security weaknesses.",
    fix:
      "Use safer input handling, validate the received value and enforce strict length or boundary checks before processing it.",
  },

  {
    id: 2,
    severity: "MEDIUM",
    title: "Missing Input Validation",
    line: "Line 08",
    short:
      "Input may be used without sufficient validation.",
    why:
      "Data coming from an external source should be validated before it is trusted by the application.",
    impact:
      "Unexpected or malformed input may reach sensitive application logic.",
    fix:
      "Validate the expected format, range and permitted characters before using the input.",
  },

  {
    id: 3,
    severity: "LOW",
    title: "Limited Error Handling",
    line: "Line 12",
    short:
      "Security-sensitive operations may require clearer error handling.",
    why:
      "Generic or missing error handling can make failures more difficult to control and investigate.",
    impact:
      "Unexpected application states may become harder to detect during execution.",
    fix:
      "Add controlled error handling and avoid exposing unnecessary internal information.",
  },
];


function AnalysisDashboard() {
  const location = useLocation();
  const navigate = useNavigate();

  const [copied, setCopied] = useState(false);
  const [openFinding, setOpenFinding] = useState(1);


  const fileName =
    location.state?.fileName || "secure-login.cpp";

  const receivedLanguage =
    location.state?.language || "C++";

  const language =
    receivedLanguage === "Auto Detect"
      ? "C++"
      : receivedLanguage;


  const sourceCode =
    location.state?.code ||
`int main() {
  char user[10];

  cin >> user;

  return 0;
}`;


  const correctedCode =
`#include <iostream>
#include <string>

int main() {
    std::string user;

    std::getline(std::cin, user);

    const std::size_t MAX_ALLOWED_LENGTH = 50;

    if (user.empty() || user.length() > MAX_ALLOWED_LENGTH) {
        std::cerr << "Invalid input." << std::endl;
        return 1;
    }

    std::cout << "Input accepted." << std::endl;

    return 0;
}`;


  const handleCopyCode = async () => {
    try {
      await navigator.clipboard.writeText(correctedCode);

      setCopied(true);

      setTimeout(() => {
        setCopied(false);
      }, 1800);
    } catch (error) {
      console.error("Unable to copy code:", error);
    }
  };


  const handleNewReview = () => {
    navigate("/features");
  };


  const handleDownloadReport = () => {
    const report = `
SECURECODE AI
SECURITY ANALYSIS REPORT

File:
${fileName}

Language:
${language}

Security Score:
78 / 100

Status:
Needs Review

Analysis Time:
2.4 seconds

Severity Summary:
Critical: 0
High: 2
Medium: 3
Low: 1


DETECTED VULNERABILITIES

1. HIGH - Unsafe Input Handling
Affected Line: 03

Potential unsafe handling of user-controlled input.

Recommended Fix:
Use validated and bounded input handling.


2. MEDIUM - Missing Input Validation
Affected Line: 08

Validate external input before processing it.


3. LOW - Limited Error Handling
Affected Line: 12

Use controlled error handling for sensitive operations.


CORRECTED CODE

${correctedCode}


Generated by SecureCode AI
Demo frontend security report.
`;


    const blob = new Blob(
      [report],
      {
        type: "text/plain",
      }
    );

    const downloadUrl =
      URL.createObjectURL(blob);

    const anchor =
      document.createElement("a");

    anchor.href = downloadUrl;

    anchor.download =
      "SecureCode-AI-Security-Report.txt";

    anchor.click();

    URL.revokeObjectURL(downloadUrl);
  };


  const toggleFinding = (id) => {
    setOpenFinding((current) =>
      current === id ? null : id
    );
  };


  return (
    <main className="dashboard-page">

      {/* ===============================
          BACKGROUND VISUALS
      =============================== */}

      <div className="dashboard-grid-background" />

      <div className="dashboard-glow dashboard-glow-one" />
      <div className="dashboard-glow dashboard-glow-two" />

      <span className="dashboard-floating-symbol dashboard-symbol-one">
        {"</>"}
      </span>

      <span className="dashboard-floating-symbol dashboard-symbol-two">
        {"{ }"}
      </span>

      <span className="dashboard-floating-symbol dashboard-symbol-three">
        AI
      </span>


      {/* ===============================
          HEADER
      =============================== */}

      <header className="dashboard-header">

        <Link
          to="/home"
          className="dashboard-brand"
        >
          <span className="dashboard-brand-icon">
            <ShieldCheck
              size={27}
              strokeWidth={1.9}
            />
          </span>

          <span className="dashboard-brand-name">
            SecureCode <strong>AI</strong>
          </span>
        </Link>


        <button
          type="button"
          className="dashboard-new-review"
          onClick={handleNewReview}
        >
          <RotateCcw size={19} />

          New Review
        </button>

      </header>


      <div className="dashboard-container">

        {/* ===============================
            INTRO
        =============================== */}

        <section className="dashboard-intro">

          <div className="dashboard-intro-left">

            <div className="analysis-complete-badge">
              <CircleCheck size={17} />

              ANALYSIS COMPLETE
            </div>

            <h1>
              Security Analysis
            </h1>

            <p>
              Review identified risks, affected code,
              security insights and recommended remediation.
            </p>


            <div className="dashboard-file-meta">

              <FileCode2 size={20} />

              <span>{fileName}</span>

              <i />

              <span>{language}</span>

              <i />

              <span className="complete-meta">
                Completed
              </span>

            </div>

          </div>


          <div className="dashboard-engine-status">

            <span className="engine-live-dot" />

            <div>
              <small>
                SECURECODE ENGINE
              </small>

              <strong>
                Analysis Ready
              </strong>
            </div>

          </div>

        </section>



        {/* ===============================
            SUMMARY CARDS
        =============================== */}

        <section className="dashboard-summary-grid">

          {/* LANGUAGE */}

          <article className="summary-card">

            <div className="summary-card-header">

              <span>Language</span>

              <div className="summary-icon">
                <Code2 size={21} />
              </div>

            </div>

            <strong className="summary-main-value">
              {language}
            </strong>

            <p>
              Source language detected
            </p>

          </article>


          {/* SCORE */}

          <article className="summary-card security-score-card">

            <div className="summary-card-header">

              <span>Security Score</span>

              <div className="summary-icon">
                <ShieldCheck size={21} />
              </div>

            </div>


            <div className="score-content">

              <div className="security-score-ring">

                <div>
                  <strong>78</strong>

                  <span>/100</span>
                </div>

              </div>


              <div className="score-text">

                <strong>
                  Needs Review
                </strong>

                <p>
                  Security improvements recommended
                </p>

              </div>

            </div>

          </article>


          {/* STATUS */}

          <article className="summary-card">

            <div className="summary-card-header">

              <span>Status</span>

              <div className="summary-icon warning-summary-icon">
                <ShieldAlert size={21} />
              </div>

            </div>

            <strong className="summary-main-value status-review">
              Needs Review
            </strong>

            <p>
              Potential risks detected
            </p>

          </article>


          {/* ANALYSIS TIME */}

          <article className="summary-card">

            <div className="summary-card-header">

              <span>Analysis Time</span>

              <div className="summary-icon">
                <Clock size={21} />
              </div>

            </div>

            <strong className="summary-main-value">
              2.4 sec
            </strong>

            <p>
              Security review completed
            </p>

          </article>

        </section>



        {/* ===============================
            SEVERITY
        =============================== */}

        <section className="dashboard-section severity-section">

          <div className="dashboard-section-heading">

            <div>
              <span>
                SECURITY OVERVIEW
              </span>

              <h2>
                Severity Summary
              </h2>

              <p>
                Findings grouped by their estimated
                security impact.
              </p>
            </div>

            <TriangleAlert size={25} />

          </div>


          <div className="severity-layout">

            <div className="severity-card-grid">

              <article className="severity-card severity-critical">

                <span>
                  Critical
                </span>

                <strong>
                  00
                </strong>

                <p>
                  Immediate risks
                </p>

              </article>


              <article className="severity-card severity-high">

                <span>
                  High
                </span>

                <strong>
                  02
                </strong>

                <p>
                  Priority findings
                </p>

              </article>


              <article className="severity-card severity-medium">

                <span>
                  Medium
                </span>

                <strong>
                  03
                </strong>

                <p>
                  Review recommended
                </p>

              </article>


              <article className="severity-card severity-low">

                <span>
                  Low
                </span>

                <strong>
                  01
                </strong>

                <p>
                  Minor findings
                </p>

              </article>

            </div>


            {/* DISTRIBUTION */}

            <div className="risk-distribution-card">

              <div className="risk-distribution-heading">

                <div>
                  <span>
                    RISK DISTRIBUTION
                  </span>

                  <h3>
                    Finding Distribution
                  </h3>
                </div>

                <ScanSearch size={22} />

              </div>


              <div className="risk-distribution-list">

                <div className="risk-distribution-row">

                  <div className="risk-row-label">
                    <span>High</span>
                    <strong>02</strong>
                  </div>

                  <div className="risk-progress-track">
                    <span className="risk-progress-high" />
                  </div>

                </div>


                <div className="risk-distribution-row">

                  <div className="risk-row-label">
                    <span>Medium</span>
                    <strong>03</strong>
                  </div>

                  <div className="risk-progress-track">
                    <span className="risk-progress-medium" />
                  </div>

                </div>


                <div className="risk-distribution-row">

                  <div className="risk-row-label">
                    <span>Low</span>
                    <strong>01</strong>
                  </div>

                  <div className="risk-progress-track">
                    <span className="risk-progress-low" />
                  </div>

                </div>

              </div>

            </div>

          </div>

        </section>



        {/* ===============================
            VULNERABILITIES
        =============================== */}

        <section className="dashboard-section vulnerabilities-section">

          <div className="dashboard-section-heading">

            <div>
              <span>
                SECURITY FINDINGS
              </span>

              <h2>
                Detected Vulnerabilities
              </h2>

              <p>
                Review potential security issues found
                during the code analysis.
              </p>
            </div>

            <Bug size={25} />

          </div>


          <div className="vulnerability-list">

            {demoVulnerabilities.map((finding) => {

              const isOpen =
                openFinding === finding.id;

              return (
                <article
                  key={finding.id}
                  className={`vulnerability-card severity-${finding.severity.toLowerCase()}-finding ${
                    isOpen
                      ? "vulnerability-card-open"
                      : ""
                  }`}
                >

                  <button
                    type="button"
                    className="vulnerability-main"
                    onClick={() =>
                      toggleFinding(finding.id)
                    }
                  >

                    <div className="vulnerability-left">

                      <div
                        className={`vulnerability-badge vulnerability-${finding.severity.toLowerCase()}`}
                      >
                        {finding.severity}
                      </div>


                      <div className="vulnerability-title-area">

                        <h3>
                          {finding.title}
                        </h3>

                        <p>
                          {finding.short}
                        </p>

                      </div>

                    </div>


                    <div className="vulnerability-right">

                      <span className="vulnerability-line">
                        {finding.line}
                      </span>


                      <span className="view-details-text">

                        {isOpen
                          ? "Hide Details"
                          : "View Details"}

                        {isOpen ? (
                          <ChevronUp size={19} />
                        ) : (
                          <ChevronDown size={19} />
                        )}

                      </span>

                    </div>

                  </button>


                  {isOpen && (
                    <div className="vulnerability-details">

                      <div className="finding-detail-box">

                        <span>
                          Why this matters
                        </span>

                        <p>
                          {finding.why}
                        </p>

                      </div>


                      <div className="finding-detail-box impact-box">

                        <span>
                          Potential Impact
                        </span>

                        <p>
                          {finding.impact}
                        </p>

                      </div>


                      <div className="finding-detail-box fix-box">

                        <span>
                          Recommended Fix
                        </span>

                        <p>
                          {finding.fix}
                        </p>

                      </div>

                    </div>
                  )}

                </article>
              );
            })}

          </div>

        </section>



        {/* ===============================
            CODE + AI
        =============================== */}

        <section className="dashboard-section">

          <div className="dashboard-section-heading">

            <div>
              <span>
                SECURITY CONTEXT
              </span>

              <h2>
                Code & AI Security Insight
              </h2>

              <p>
                Understand where the risk occurs
                and why it matters.
              </p>
            </div>

            <Sparkles size={25} />

          </div>


          <div className="code-insight-layout">

            {/* AFFECTED CODE */}

            <article className="affected-code-panel">

              <div className="panel-top">

                <div>
                  <FileCode2 size={21} />

                  <div>
                    <span>
                      AFFECTED CODE
                    </span>

                    <h3>
                      Vulnerable Source
                    </h3>
                  </div>

                </div>


                <span className="code-risk-badge">
                  HIGH RISK
                </span>

              </div>


              <div className="code-viewer">

                <div className="code-scan-line" />

                {sourceCode
                  .split("\n")
                  .map((line, index) => {

                    const lineNumber =
                      index + 1;

                    const risky =
                      lineNumber === 3;

                    return (
                      <div
                        className={`dashboard-code-line ${
                          risky
                            ? "dashboard-risky-code-line"
                            : ""
                        }`}
                        key={index}
                      >

                        <span className="dashboard-line-number">
                          {String(lineNumber).padStart(
                            2,
                            "0"
                          )}
                        </span>

                        <code>
                          {line || " "}
                        </code>

                        {risky && (
                          <span className="code-line-warning">
                            HIGH
                          </span>
                        )}

                      </div>
                    );
                  })}

              </div>

            </article>



            {/* AI INSIGHT */}

            <article className="ai-insight-panel">

              <div className="ai-panel-glow" />

              <div className="panel-top">

                <div>
                  <Sparkles size={21} />

                  <div>
                    <span>
                      AI SECURITY INSIGHT
                    </span>

                    <h3>
                      Intelligent Explanation
                    </h3>
                  </div>

                </div>


                <span className="ai-badge">
                  AI
                </span>

              </div>


              <div className="ai-insight-content">

                <div className="ai-insight-item">

                  <div className="ai-insight-icon">
                    <Lightbulb size={20} />
                  </div>

                  <div>
                    <h4>
                      Why this matters
                    </h4>

                    <p>
                      The detected code may accept
                      user-controlled input without
                      sufficiently restricting its size
                      or validating its contents.
                    </p>
                  </div>

                </div>


                <div className="ai-insight-item">

                  <div className="ai-insight-icon warning-ai-icon">
                    <CircleAlert size={20} />
                  </div>

                  <div>
                    <h4>
                      Potential Impact
                    </h4>

                    <p>
                      Improper input handling can cause
                      unexpected application behaviour
                      and may create exploitable security
                      conditions depending on how the
                      value is later used.
                    </p>
                  </div>

                </div>


                <div className="ai-confidence">

                  <span>
                    Analysis Confidence
                  </span>

                  <div className="ai-confidence-bar">
                    <span />
                  </div>

                  <strong>
                    92%
                  </strong>

                </div>

              </div>

            </article>

          </div>

        </section>



        {/* ===============================
            REMEDIATION
        =============================== */}

        <section className="dashboard-section">

          <div className="remediation-panel">

            <div className="remediation-icon">
              <WandSparkles size={27} />
            </div>


            <div className="remediation-content">

              <span>
                RECOMMENDED REMEDIATION
              </span>

              <h2>
                Apply Safer Input Handling
              </h2>

              <p>
                Replace fixed-size unsafe input
                handling with a safer string-based
                approach. Validate the input length
                and reject values that do not meet
                the expected security requirements.
              </p>


              <div className="remediation-points">

                <span>
                  <CircleCheck size={18} />
                  Validate user-controlled input
                </span>

                <span>
                  <CircleCheck size={18} />
                  Apply explicit length boundaries
                </span>

                <span>
                  <CircleCheck size={18} />
                  Handle invalid input safely
                </span>

              </div>

            </div>

          </div>

        </section>



        {/* ===============================
            CORRECTED CODE
        =============================== */}

        <section className="dashboard-section corrected-code-section">

          <div className="dashboard-section-heading">

            <div>
              <span>
                SECURE REMEDIATION
              </span>

              <h2>
                Corrected / Secure Code
              </h2>

              <p>
                Review the suggested safer
                implementation before applying it.
              </p>
            </div>

            <ShieldCheck size={25} />

          </div>


          <div className="corrected-code-card">

            <div className="corrected-code-toolbar">

              <div className="corrected-code-file">

                <FileCode2 size={20} />

                <div>
                  <strong>
                    secure-fix.cpp
                  </strong>

                  <span>
                    Suggested remediation
                  </span>
                </div>

              </div>


              <button
                type="button"
                className={`copy-code-button ${
                  copied
                    ? "copy-code-success"
                    : ""
                }`}
                onClick={handleCopyCode}
              >

                {copied ? (
                  <>
                    <Check size={18} />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy size={18} />
                    Copy Code
                  </>
                )}

              </button>

            </div>


            <div className="corrected-code-viewer">

              {correctedCode
                .split("\n")
                .map((line, index) => (
                  <div
                    className="secure-code-line"
                    key={index}
                  >

                    <span>
                      {String(index + 1).padStart(
                        2,
                        "0"
                      )}
                    </span>

                    <code>
                      {line || " "}
                    </code>

                  </div>
                ))}

            </div>

          </div>

        </section>

        {/* =========================================
    SECURITY FIX COMPARISON
========================================= */}

<section className="dashboard-section fix-comparison-section">

  <div className="dashboard-section-heading">
    <div>
      <span>SECURITY FIX COMPARISON</span>

      <h2>
        Why is the corrected code better?
      </h2>
    </div>

    <p>
      Compare the original implementation with the recommended secure
      version and understand why the suggested code is safer.
    </p>
  </div>


  {/* ORIGINAL VS CORRECTED */}

  <div className="fix-comparison-grid">

    {/* ORIGINAL */}
    <article className="comparison-code-card original-comparison-card">

      <div className="comparison-card-header">

        <div className="comparison-header-icon original-icon">
          <TriangleAlert size={23} />
        </div>

        <div>
          <span>USER SUBMISSION</span>
          <h3>Original Code</h3>
        </div>

        <span className="comparison-status original-status">
          NEEDS REVIEW
        </span>

      </div>


      <div className="comparison-summary">

        <div>
          <span>Security Status</span>
          <strong className="comparison-risk-text">
            Higher Risk
          </strong>
        </div>

        <div>
          <span>Detected Issue</span>
          <strong>
            Unsafe Input Handling
          </strong>
        </div>

        <div>
          <span>Severity</span>
          <strong className="comparison-high-text">
            HIGH
          </strong>
        </div>

      </div>


      <div className="comparison-explanation">

        <span>WHY THIS CODE IS AFFECTED</span>

        <p>
          The original implementation accepts input without clearly
          enforcing a safe input boundary. In a fixed-size memory
          structure, oversized input may exceed the expected capacity
          and create unsafe program behaviour.
        </p>

      </div>


      <div className="comparison-points">

        <span className="comparison-negative-point">
          <TriangleAlert size={17} />
          Input boundary is not clearly controlled
        </span>

        <span className="comparison-negative-point">
          <TriangleAlert size={17} />
          Risky input handling pattern remains present
        </span>

        <span className="comparison-negative-point">
          <TriangleAlert size={17} />
          Additional validation is required
        </span>

      </div>

    </article>



    {/* CORRECTED */}
    <article className="comparison-code-card corrected-comparison-card">

      <div className="comparison-card-header">

        <div className="comparison-header-icon corrected-icon">
          <ShieldCheck size={23} />
        </div>

        <div>
          <span>SECURE RECOMMENDATION</span>
          <h3>Corrected Code</h3>
        </div>

        <span className="comparison-status corrected-status">
          RECOMMENDED
        </span>

      </div>


      <div className="comparison-summary">

        <div>
          <span>Security Status</span>
          <strong className="comparison-safe-text">
            Safer
          </strong>
        </div>

        <div>
          <span>Risk Handling</span>
          <strong>
            Improved
          </strong>
        </div>

        <div>
          <span>Recommendation</span>
          <strong className="comparison-safe-text">
            ACCEPT
          </strong>
        </div>

      </div>


      <div className="comparison-explanation">

        <span>WHY THIS CODE IS RECOMMENDED</span>

        <p>
          The corrected implementation uses safer input handling and
          introduces explicit validation. This reduces the identified
          risk while preserving the intended behaviour of the original
          program.
        </p>

      </div>


      <div className="comparison-points">

        <span className="comparison-positive-point">
          <CircleCheck size={17} />
          Safer input handling strategy
        </span>

        <span className="comparison-positive-point">
          <CircleCheck size={17} />
          Explicit validation improves control
        </span>

        <span className="comparison-positive-point">
          <CircleCheck size={17} />
          Original functionality is preserved
        </span>

      </div>

    </article>

  </div>



  {/* WHY BETTER */}

  <div className="why-better-panel">

    <div className="why-better-heading">

      <div className="why-better-icon">
        <WandSparkles size={25} />
      </div>

      <div>
        <span>AI SECURITY REASONING</span>
        <h3>Why choose the corrected code?</h3>
      </div>

    </div>


    <div className="why-better-grid">

      <article>
        <span>01</span>

        <h4>Security</h4>

        <p>
          The identified unsafe input pattern is replaced with a safer
          approach that provides better control over received data.
        </p>
      </article>


      <article>
        <span>02</span>

        <h4>Validation</h4>

        <p>
          The recommended implementation validates the input instead of
          blindly accepting arbitrary data.
        </p>
      </article>


      <article>
        <span>03</span>

        <h4>Functionality</h4>

        <p>
          The corrected version is designed to preserve the original
          purpose of the program while improving its security.
        </p>
      </article>


      <article>
        <span>04</span>

        <h4>Maintainability</h4>

        <p>
          Clearer and safer handling makes the implementation easier to
          understand, review and improve in the future.
        </p>
      </article>

    </div>

  </div>



  {/* FINAL VERDICT */}

  <div className="fix-verdict-panel">

    <div className="fix-verdict-icon">
      <ShieldCheck size={28} />
    </div>


    <div className="fix-verdict-content">

      <span>FINAL RECOMMENDATION</span>

      <h3>
        Corrected Code is the recommended implementation.
      </h3>

      <p>
        It addresses the identified security concern while maintaining
        the intended behaviour of the submitted code. The recommendation
        is based on improved input safety, validation and secure coding
        practice.
      </p>

    </div>


    <div className="fix-verdict-badge">
      <CircleCheck size={18} />
      BETTER CHOICE
    </div>

  </div>

</section>



        {/* ===============================
            BOTTOM ACTIONS
        =============================== */}

        <section className="dashboard-bottom-actions">

          <div>

            <ShieldCheck size={22} />

            <p>
              Security analysis completed.
              Review all findings before applying
              suggested changes.
            </p>

          </div>


          <div className="dashboard-action-buttons">

            <button
              type="button"
              className="bottom-new-review-button"
              onClick={handleNewReview}
            >
              <RotateCcw size={19} />

              New Review
            </button>


            <button
              type="button"
              className="download-report-button"
              onClick={handleDownloadReport}
            >
              <Download size={19} />

              Download Report
            </button>

          </div>

        </section>

      </div>
      {/* BACK TO FEATURES */}

<div className="dashboard-back-features">
  <button
    type="button"
    className="back-features-arrow"
    onClick={() => navigate("/features")}
    aria-label="Back to Code Review"
  >
    <ChevronDown size={28} />
  </button>

  <span>Back to Code Review</span>
</div>


      <footer className="dashboard-footer">

        <ShieldCheck size={18} />

        SecureCode AI · Intelligent Security Analysis

      </footer>

    </main>
  );
}


export default AnalysisDashboard;